success
mate-academy/react_people-table-advanced pull request #1054
Opened 2024-09-10 08:48 UTC by vladisssi

[DEMO LINK](https://vladisssi.github.io/react_people-table-advanced/)

2024-09-10 13:36 UTC, vladisssi commented
![Uploading Screenshot 2024-09-10 at 16.33.57.png…]()

2024-09-10 14:20 UTC, volodymyr-soltys97 requested changes
Hi, your demo link isn't working, you need to make a deploy and check it after on the demo 
<img width="855" alt="image" src="https://github.com/user-attachments/assets/61fe8e48-3a52-4505-b962-da8dbc8b9f57">

2024-09-10 17:21 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code
1. Don't need to reset filters after clicking on the person 
<img width="597" alt="image" src="https://github.com/user-attachments/assets/262d5116-b471-4acb-a95d-d284967d6f2e">
<img width="252" alt="image" src="https://github.com/user-attachments/assets/065fe8f9-2b62-4b93-ab50-bcbcdee6adb5">
<img width="307" alt="image" src="https://github.com/user-attachments/assets/facd05db-bd82-4882-8f64-300a0008283f">

2. Clear the selected people after reset all filters 
<img width="289" alt="image" src="https://github.com/user-attachments/assets/1b4aa7b0-b427-4b51-a3d2-ab2bb0df3201">

2024-09-10 17:21 UTC, volodymyr-soltys97 commented on src/components/PeopleFilters.tsx
> +  const centuriesArray = ['16', '17', '18', '19', '20'];
This array needs to be memorized

2024-09-10 17:21 UTC, volodymyr-soltys97 commented on src/utils/ways.ts
> +export enum WAYS {
```suggestion
export enum ERoutes {
```

2024-09-10 18:29 UTC, vladisssi commented
in demo link we need to reset filters after clicking on the person

2024-09-10 19:15 UTC, etojeDenys requested changes

2024-09-10 19:15 UTC, etojeDenys commented on src/utils/filterPeople.ts
> +
```suggestion
        case 'name':
        case 'sex':
          return a[sort].localeCompare(b[sort]);

```
you can combine cases

2024-09-10 19:15 UTC, etojeDenys commented on src/utils/filterPeople.ts
> +          return a[sort] - b[sort];
same here

2024-09-11 19:05 UTC, VitaliyBondarenko1982 requested changes
Not fixed 1st point  from the [comment](https://github.com/mate-academy/react_people-table-advanced/pull/1054#pullrequestreview-2293197759)

after click on person filters shouldn't reset

https://github.com/user-attachments/assets/554a51e0-9b77-4d80-9532-655659d51ef7

2024-09-15 11:37 UTC, closed without merging