Solution
mate-academy/react_people-table-advanced pull request #386
Opened 2023-08-09 14:22 UTC by outofs

https://outofs.github.io/react_people-table-advanced/

2023-08-10 07:11 UTC, perfectAcedia commented on src/components/PeopleFilters.tsx
> +  All = 'all',
This type is unused, so I guess you can remove "All".

2023-08-10 07:42 UTC, perfectAcedia approved these changes
Looks good, but I found a few issues. 
Firstly, switch pages between Home and People, you will see short table loading, try to remove it.
Then, I found that "arrow sorting" saves sort params in the URL but does not remove them once sorting is disabled. Also, after the first click on the sort button, both(sort and order) fields appear. It shouldn't work like this I guess.
First click -> only sort field
Second click -> sort + order field
Third click -> both fields should be removed from the URL bar.
![image](https://github.com/mate-academy/react_people-table-advanced/assets/123010302/48f651a3-5f30-48ab-ba0e-8d8cb8266104)

2023-08-10 08:04 UTC, anstsot requested changes
Let’s add a few fixes to improve your code.
- Test should be visible onle
![image](https://github.com/mate-academy/react_people-table-advanced/assets/22824431/07b186ac-c498-4992-a660-ff198f365f8a)

2023-08-10 08:04 UTC, anstsot commented on src/pages/PeoplePage.tsx
> +  const preparedPeople = preparePeople(
`useMemo` can be used

2023-08-10 08:04 UTC, anstsot commented on src/components/PeopleFilters.tsx
> +enum Sex {
better to move in `typings` folder

2023-08-10 08:04 UTC, anstsot commented on src/components/PeopleRow.tsx
> +    () => findLinkedPerson(person.motherName || '', people), [],
add missing deps
```suggestion
    () => findLinkedPerson(person.motherName || '', people), [people],
```

2023-08-11 07:30 UTC, anstsot approved these changes
Good work, approving:sparkles:

2025-12-01 12:28 UTC, closed without merging