commit
mate-academy/react_people-table-advanced pull request #448
Opened 2023-09-05 16:57 UTC by anastasia-radchencko

https://anastasia-radchencko.github.io/react_people-table-advanced/

2023-09-05 17:18 UTC, TarasHoliuk requested changes
You should add routes in the App.tsx to display the correct page:
![image](https://github.com/mate-academy/react_people-table-advanced/assets/86923089/5559c8fa-e252-416f-b84c-e762c6c48758)
![image](https://github.com/mate-academy/react_people-table-advanced/assets/86923089/b811314c-aec0-426f-bfb9-0c6f8dc92636)

2023-09-05 17:18 UTC, TarasHoliuk commented on src/components/PersonLink.tsx
> +        'has-background-warning': slugValue === slug,
it doesn't work
![image](https://github.com/mate-academy/react_people-table-advanced/assets/86923089/10bbd0ee-dbd4-4eed-b457-2a8c1ff3d259)

2023-09-05 17:18 UTC, TarasHoliuk commented on src/components/PeopleFilters.tsx
>                className="button is-success is-outlined"
should be filled if no filters selected

2023-09-06 06:43 UTC, etojeDenys requested changes
let's try to fix your routes
<img width="530" alt="image" src="https://github.com/mate-academy/react_people-table-advanced/assets/70220667/c61a7b94-3282-442d-b353-3ad0bc664894">



or feel free to ask in chat for some help

2023-09-06 06:43 UTC, etojeDenys commented on src/components/PeoplePage.tsx
> +              {false && (
it will be always hidden

2023-09-06 17:43 UTC, closed without merging