table_advansed
mate-academy/react_people-table-advanced pull request #639
Opened 2023-12-05 18:03 UTC by MaksymKos

https://maksymkos.github.io/react_people-table-advanced/

2023-12-06 09:43 UTC, VitaliyBondarenko1982 requested changes
Looks good.
Compare your implementation with working example.
А couple mismatches founded.
- when exists some searchParams and click on person link - searchParams shouldn't be resetted
- when order in desc direction- should be visible only bottom arrow 
actual:
![actual](https://github.com/mate-academy/react_people-table-advanced/assets/33029864/b2f9badd-1843-4c0a-9847-170159fb6ab1)
working example:
![working_example](https://github.com/mate-academy/react_people-table-advanced/assets/33029864/6bc3e4a7-500c-4c3c-891c-14b8d4193ca8)

2023-12-06 09:43 UTC, VitaliyBondarenko1982 commented on src/components/PeopleFilters.tsx
> +  const query = searchParams.get('query') || '';
suggest to make enum for all possible searchParams

2023-12-08 18:32 UTC, etojeDenys requested changes
i cannot find PeopleTable component in github

2023-12-08 18:32 UTC, etojeDenys commented on src/components/PeoplePage.tsx
> +        }
```suggestion
        case 'name':
        case 'sex':
        {
          prepared.sort((a, b) => a[sort].localeCompare(b[sort]));
          break;
        }
```
you can group some cases

2023-12-09 13:41 UTC, VitaliyBondarenko1982 approved these changes
Well done.

2024-10-14 06:10 UTC, closed without merging