Develop
mate-academy/react_people-table-advanced pull request #760
Opened 2024-02-20 14:31 UTC by MarkiMark3

[DEMO LINK](https://MarkiMark3.github.io/react_people-table-advanced/)

2024-02-20 16:12 UTC, etojeDenys requested changes

2024-02-20 16:12 UTC, etojeDenys commented on src/components/PersonLink.tsx
> +  const father = people.filter(dad => dad.name === person.fatherName)[0];
better to use find method instead of filter, 'cause you want to find the element not filter the array

2024-02-20 16:12 UTC, etojeDenys commented on src/components/PeoplePage.tsx
> +          return a.sex.localeCompare(b.sex);
```suggestion
        case 'name':
        case 'sex':
          return a[sorter].localeCompare(b[sorter]);
```
you can group the cases

2024-02-20 16:12 UTC, etojeDenys commented on src/components/PeoplePage.tsx
> +          return a.died - b.died;
same here

2024-02-21 16:04 UTC, etojeDenys requested changes
you don't need to reset the sort and filter options when you click on the person


https://github.com/mate-academy/react_people-table-advanced/assets/70220667/a3122640-9722-459a-aaea-06c1145e2e07

2024-02-21 16:04 UTC, etojeDenys commented on src/components/PeoplePage.tsx
> +    }
looks strange and too complicated you can just reverse the array after sorting if order exists

2024-02-21 18:27 UTC, etojeDenys requested changes
still can reproduce the same error


Якщо раптом щось із моїх коментарів тобі незрозуміло, то, будь ласка, не чекай і звертайся у чат з менторами або приходь на Q&A сесію. Обовʼязково з усім розберемось)

2024-02-21 19:54 UTC, MarkiMark3 commented
I fixed it last time its just not deploying properly it works as intended on my server

2024-02-22 08:10 UTC, etojeDenys requested changes
створи повідомлення стосовно проблеми деплою і тегни мене в коментах у ньому, або активного ментора своєї групи

2024-02-22 14:55 UTC, closed without merging